---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidymodels)
library(multipanelfigure)
library(ggrepel)
series_from_imdb <- read_csv("data/series_from_imdb.csv")

nex_raw <- series_from_imdb %>% filter(series_name=="Northern Exposure") %>% 
  select(-starts_with("r"))

nex_raw %>% ggplot(aes(user_rating)) + geom_histogram()
```

```{r}
nex_raw %>% ggplot(aes(user_votes,user_rating)) + geom_point() + geom_smooth()
```
```{r,fig.height=6}
season_color = "blue"
trend_color = "red"
# classify episodes by popularity quintile
# create labels for best and worst
# percentiles = 10
# nex <- nex %>% 
#   mutate(percentile=cut_number(user_rating,n=percentiles,labels=FALSE)) %>% 
#   mutate(point_labels = ifelse(percentile == percentiles | percentile == 1,episode,NA))

season_rating <- nex %>% 
  group_by(season) %>% 
  summarise(user_rating=min(user_rating)) %>%
  mutate(rating="lowest") 

nex <- nex_raw %>%  
  group_by(season) %>% 
  summarise(user_rating=max(user_rating)) %>%
  mutate(rating="highest") %>% 
  bind_rows(season_rating) %>% 
  right_join(nex) %>% 
  mutate(point_labels = ifelse(is.na(rating),NA,episode)) %>% 
  arrange(series_ep)

#get season breaks
breaks=c(0,which(diff(nex$season)!=0),nrow(nex)) + 0.5
seasons = unique(nex$season)
g1 = nex %>% ggplot(aes(series_ep,user_rating,label=point_labels)) + 
  geom_point() +
  labs(x=NULL,
       y = "IMDB User Average Rating",
       title = "Northern Exposure: User Ratings from IMBD.com ") +
  geom_vline(xintercept = breaks,color=season_color) +
  geom_smooth(aes(group=season),method="lm",se=FALSE,color=trend_color) +
  annotate("text",x=breaks[1:max(seasons)] + 5,y = 5.5,label = seasons,color = season_color) +
  annotate("text",x=breaks[3]+10 ,y = 6.0,label = "Season", color = season_color) +
  theme_minimal() +
  theme(panel.grid = element_blank(),axis.text.x = element_blank()) +
  geom_text_repel()

g2 = nex %>% ggplot(aes(series_ep,user_votes)) + geom_col() +
  geom_vline(xintercept = breaks,color=season_color) +
  theme_minimal() +
  theme(panel.grid = element_blank(),axis.text.x = element_blank()) +
  labs(y = "IMDB User Votes",
       x= NULL)

gg <- multi_panel_figure(columns = 1,rows = 5)

gg %>% 
  fill_panel(g1,row=c(1:3),column = 1) %>% 
  fill_panel(g2,row=c(4,5),column = 1)
```

